### PR TITLE
Great improvements

### PR DESCRIPTION
**Pull request by marharyta**
Did some improvements to the website:

- now we use parcel as bundler
- we have sass instead of manual css with manual minification (with postcss and autoprefixer for backwards compatibility)
- I have cleaned some DOM elements (they were a hot mess)
- I have generated /dist folder with supported hashing

before:
Screen Shot 2019-04-04 at 12 42 31
Screen Shot 2019-04-04 at 12 42 27

after:
Screen Shot 2019-04-04 at 12 42 06
Screen Shot 2019-04-04 at 12 42 38

### CODE REVIEW

**Comment by d2s** [comment]
Looks good. 👍

**Comment by marharyta** [comment]
@eemeli Good catch!
Regarding the issue 1, can you give me more info?
Issue 2, can I get a screenshot and dimensions?
Thanks for reviewing!

**Comment by eemeli** [comment]
1. When I run `npx serve` in the `dist/` folder and open the page, I see an error in the JS console:
    ```
    WebSocket connection to 'ws://localhost:63891/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
    ```
2. After a bit more testing, the trigger isn't the size of the content, but whether the window is shorter than it is wide. When that happens, this is how it looks like to me: Screenshot 2019-04-06 at 11 05 32

**Comment by marharyta** [comment]
@eemeli thank you!

**Comment by marharyta** [comment]
@eemeli should be all fixed now ❤️

**Comment by eemeli** [comment]
It does look all fixed! :)

Presumably the dist/ folder could/should be removed?

**Comment by marharyta** [comment]
@eemeli oops, yep.
Should delete it in a next PR?

**Comment by d2s** [comment]
CSS styles are now broken, because https://helsinkijs.org/index.js file contains only:
```js
import './style.scss'
```

screencapture-helsinkijs-org-2019-05-13-16_06_21

**Comment by eemeli** [comment]
Should now be all fixed. The actual mistake (mine) was not updating the GitHub settings to read stuff from `docs/` rather than the root, but I also added npm scripts to properly publish a production build. As it turns out, with this setup the magic `CNAME` file also needs to be in the `docs/` directory.

**Comment by hugovk** [comment]
Looking good!

**Pull request merged**
