### PR TITLE
feat: aurora effect

### PR DESCRIPTION
**Pull request by marharyta**
Quite a big design change, but oh boy it is fun!
https://user-images.githubusercontent.com/7344718/209134281-f4013edb-dc34-4c1d-98ac-7d4839d6963d.mp4

### CODE REVIEW

**Review by eemeli — APPROVED** [review]
I don't really have capacity to review this properly, so let's just deploy it and see how it goes?

**Comment by marharyta** [comment]
👍🏻 lets do that

**Comment by eemeli** [comment]
@marharyta You should have write access already so feel free to press teh button. IIRC deployment might need a separate action, as the site is served from the `docs/` directory.

**Comment by marharyta** [comment]
speaking of, who is in charge of deploy here? lol @eemeli @olegp

**Comment by olegp** [comment]
@eemeli would you have time to review?

**Pull request merged**
